apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-wtjx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-wtjx
    app.kubernetes.io/part-of: load-app-2f2fd795-e314-4d69-8b25-6572437dccc9
  name: devfile-sample-code-with-snjk
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: devfile-sample-code-with-quarkus-wtjx
    weight: null
status: {}
